// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ardjxmurnswohqotlyus.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFyZGp4bXVybnN3b2hxb3RseXVzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzUwNTA2NTEsImV4cCI6MjA5MDYyNjY1MX0.CO4GoFW1K5UdJ22AV1U9x1w9JMYuHsoV5NFGNjTZTY0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});